name: Pull Request Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  runcheck:
    name: Check if run-ci is requested
    runs-on: ubuntu-20.04
    outputs:
      cirun: ${{ steps.check.outputs.cirun }}

    steps:
    - name: Check
      id: check
      run: |
        if [ ${{ github.event_name }} == pull_request ]; then
          sha=${{ github.event.pull_request.head.sha }}
          url=$(echo ${{ github.event.pull_request.head.repo.git_commits_url }} | sed "s:{/sha}:/$sha:")
        elif [ ${{ github.event_name }} == push ]; then
          sha=${{ github.event.after }}
          url=$(echo ${{ github.event.repository.git_commits_url }} | sed "s:{/sha}:/$sha:")
        fi

        message="$(curl -sS -H $app $url | jq '.message')"
        echo $message | grep run-ci >/dev/null 2>&1 && d=$? || d=$?
        if [ $d -eq 0 ]; then
          echo "::set-output name=cirun::yes"
        elif [ $d -eq 1 ]; then
          echo "::set-output name=cirun::no"
        fi
        printf "Commit message is %s\n" "$message"

  build:
    name: Build ${{ matrix.build_no }}
    needs: runcheck
    runs-on: ubuntu-20.04
    if: needs.runcheck.outputs.cirun == 'yes'
    strategy:
      fail-fast: false
      matrix:
        build_no: [1, 2, 3]

    steps:
    - name: Build step 1
      run: |
        sleep 20
        echo "I am building"
        if [ ${{ matrix.build_no }} == 1 ]; then
          exit 1
        fi

  waitec2:
    name: Wait
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Retrieve helper id
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/helper_id_file
        key: helperid-${{ github.run_id }}

    - name: Check if ec2 instances started
      run: |
        helper_id=$(cat ${{ github.workspace }}/helper_id_file)
        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
        ec2_started=$(echo -n $url | ./job_status_check.py startrunner_check)
        if [ $ec2_started != 'success' ]; then
          echo "EC2 instances did not start"
          exit 1
        fi

  test:
    name: Test ${{ matrix.trial }}
    needs: waitec2
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        trial: [1, 2, 3]


    steps:
    - name: Test step 1
      run: |
        sleep 60
        echo "I am testing"
